export const fields = [
  { name: "email", type: "email", header: "Email" },
  { name: "fullName", type: "text", header: "Nombre completo:" },
  { name: "age", type: "number", header: "Edad:" },
  { name: "username", type: "text", header: "Nombre de usuario:" },
];

export const countries = [
  "Selecciona un país",
  "Afganistán",
  "Albania",
  "Argelia",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Baréin",
  "Bangladés",
  "Barbados",
  "Bielorrusia",
  "Bélgica",
  "Belice",
  "Benín",
  "Bután",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "República Centroafricana",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoras",
  "República Democrática del Congo",
  "República del Congo",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Chipre",
  "República Checa",
  "Dinamarca",
  "Yibuti",
  "Dominica",
  "República Dominicana",
  "Timor Oriental (Timor-Leste)",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Guinea Ecuatorial",
  "Eritrea",
  "Estonia",
  "Esuatini",
  "Etiopía",
  "Fiyi",
  "Finlandia",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Alemania",
  "Ghana",
  "Grecia",
  "Granada",
  "Guatemala",
  "Guinea",
  "Guinea-Bisáu",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "Islandia",
  "India",
  "Indonesia",
  "Irán",
  "Irak",
  "Irlanda",
  "Israel",
  "Italia",
  "Costa de Marfil",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kirguistán",
  "Laos",
  "Letonia",
  "Líbano",
  "Lesoto",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Madagascar",
  "Malaui",
  "Malasia",
  "Maldivas",
  "Malí",
  "Malta",
  "Islas Marshall",
  "Mauritania",
  "Mauricio",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Marruecos",
  "Mozambique",
  "Myanmar (Birmania)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Países Bajos",
  "Nueva Zelanda",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Corea del Norte",
  "Macedonia del Norte (anteriormente Macedonia)",
  "Noruega",
  "Omán",
  "Pakistán",
  "Palaos",
  "Palestina",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Filipinas",
  "Polonia",
  "Portugal",
  "Catar",
  "Rumania",
  "Rusia",
  "Ruanda",
  "San Cristóbal y Nieves",
  "Santa Lucía",
  "San Vicente y las Granadinas",
  "Samoa",
  "San Marino",
  "Santo Tomé y Príncipe",
  "Arabia Saudita",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Eslovaquia",
  "Eslovenia",
  "Islas Salomón",
  "Somalia",
  "Sudáfrica",
  "Corea del Sur",
  "Sudán del Sur",
  "España",
  "Sri Lanka",
  "Sudán",
  "Surinam",
  "Suecia",
  "Suiza",
  "Siria",
  "Taiwán",
  "Tayikistán",
  "Tanzania",
  "Tailandia",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turquía",
  "Turkmenistán",
  "Tuvalu",
  "Uganda",
  "Ucrania",
  "Emiratos Árabes Unidos",
  "Reino Unido",
  "Estados Unidos",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Ciudad del Vaticano",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabue",
];
